### ISSUE TITLE
Continuous re-rendering with react-router-dom

### ISSUE THREAD

**Issue by ubaidseth** [ctrlplusb/easy-peasy#266] opened 2019-07-19 00:51 UTC
I checked every single prop down from App.js to the child component and there should be no reason to re-render. I installed a script to check why and it kept pointing to the this.props.match key. Even though that key doesn't change, it still re-renders. 

This may be an issue with react-router-dom but when I uninstall easy-peasy the error goes away. I'd rather choose this module over react-router-dom -- has anyone had any success with another routing module that works much better with easy-peasy?

**Comment by ctrlplusb** [comment] 2019-07-19 07:29
Hey @ubaidseth 

Is there any chance you could create a minimal reproduction in codesandbox or share some code. I use react-router-dom extensively with no issues.

**Comment by bentron2000** [comment] 2019-07-19 07:36
@ubaidseth 
We're hunting down some extraneous re-rendering and performance issues as well and I saw this ticket - can I ask what environment you're running in? Also, are you using 'memoryRouter' perchance?

**Comment by ctrlplusb** [comment] 2019-07-19 07:57
Have you seen this? Might help 👍

https://github.com/welldone-software/why-did-you-render

**Comment by ubaidseth** [comment] 2019-07-19 12:03
Using browserHistory. Env is a linux debian 9

**Comment by ctrlplusb** [comment] 2019-07-23 00:00
Hi both, I am going to close this due to lack of information. If you can provide a reproducible code sandbox I would be happy to review.

**Closed by ctrlplusb** 2019-07-23 00:00 UTC
Labels: needs-investigation
