### ISSUE TITLE
Return multiple actions from useStoreActions?

### ISSUE THREAD

**Issue by joelmoss** [ctrlplusb/easy-peasy#275] opened 2019-07-25 12:24 UTC
So while the naming of `useStoreActions` would imply you can return multiple actions from a single call, is that safe/performant to do?

For example:

```javascript
  const { attachPaymentMethod, submit } = useStoreActions(x => ({
    attachPaymentMethod: x.attachPaymentMethod,
    submit: x.submit
  }))
```

I ask because it seems to be recommended that you return only a single value from `useStoreState`, so wandered if the same applies?

thx

**Comment by ctrlplusb** [comment] 2019-07-25 12:38
Completely fine to do this. 👍

**Comment by joelmoss** [comment] 2019-07-25 12:48
I figured as much, thx.

I gotta admit that it's _slightly_ annoying that when I need multiple state values from the store that I have to call `useStoreState` for each one...

```javascript
const therapistId = useStoreState(x => x.therapistId)
const submitButtonText = useStoreState(x => x.submitButtonText)
const view = useStoreState(x => x.view)
...
```

Becomes a little repetitive. With Redux, I liked being able to define a single `mapStateToProps` function to return a hash of the state that I need.

Now I know the reason for this - equality checking. But maybe some way to pass or define a custom equality function would be nifty...

```javascript
const shallow = () => { ... }
const { foo, bar } = useStoreState(state => ({ foo: state.foo, bar: state.bar }), shallow)
```

What do you think?

FYI: awesome lib! Keep up the good work 👌

**Comment by allpro** [comment] 2019-07-25 14:55
Since actions have no equality checking, I often import the entire model-actions object when I need to call _multiple_ actions from a component. I find the OOP syntax also helps readability in larger code blocks. So something like...

````javascript
const actions = useStoreActions(x => x.path.to.model);
...
actions.attachPaymentMethod(payload);
actions.submit(data);
// etc.
````

**Comment by ctrlplusb** [comment] 2019-07-25 14:57
Hey @joelmoss 

Thanks 😀

> But maybe some way to pass or define a custom equality function would be nifty

That's a pretty decent feature request. I believe the react-redux hooks do something similar. I'll take this under consideration. 👍

**Comment by joelmoss** [comment] 2019-07-25 15:02
I got the idea from Zustand https://github.com/react-spring/zustand#selecting-multiple-state-slices

**Comment by joelmoss** [comment] 2019-07-25 15:12
And as actions have no equality check, how about this to make action fetching even more easy-peasy... 😁

```javascript
const [ attachPaymentMethod, submit ] = useStoreActions('attachPaymentMethod', 'submit')
```

I created a little wrapping hook to actually enable the above...

```javascript
import { createIdentity } from 'identitate'

const useEasyActions = (...actionPaths) => {
  return useStoreActions(actions => {
    let identifiedActions = []

    for (let path of actionPaths) {
      identifiedActions.push(createIdentity(0, path)(actions))
    }

    return identifiedActions
  })
}
```

If you like, I'll try and get you a PR

**Comment by allpro** [comment] 2019-07-25 15:16
> maybe some way to pass or define a custom equality function would be nifty...

I think the problem is that your example returns a _new object_ each time. This means simple equality testing can't work, so it would add significant complexity for it to work. I doubt Sean would want that.

You can create a _computed value_ that returns an object created from multiple values. This is not _less code_ but does simplify the component syntax.

You could also import the entire parent object (the 'model state'), instead of the individual model values. This means your component would re-render if _any_ model value changes. If your component uses all model values, then this is what you want anyway. Just an idea.

**Comment by joelmoss** [comment] 2019-07-25 15:22
> I think the problem is that your example returns a new object each time

Yeah I know. Which is why the ability for passing a custom equality function would fix this.

While easy-peasy is really easy-peasy and hides a lot of the boilerplate (and it does it really well), at the same time we lose a little of the benefits of react-redux, which has slightly superior equality checking.

And this proposal allows us to potentially match that.

**Comment by allpro** [comment] 2019-07-25 15:24
> ````javascript
const [ attachPaymentMethod, submit ] = useStoreActions('attachPaymentMethod', 'submit')
````

Actions are just keys in an object so you can destructure it using the same syntax I showed above...

````javascript
const { attachPaymentMethod, submit } = useStoreActions(x => x.path.to.model);
````

**Comment by joelmoss** [comment] 2019-07-25 15:28
A result of me overthinking things 🤦‍♂️

However, one small advantage with my `useEasyActions` is the ability to pass paths...

```javascript
const [ attachPaymentMethod, submit ] = useStoreActions('path.to.model.attachPaymentMethod', 'another.model.submit')
```

**Comment by allpro** [comment] 2019-07-25 15:38
> we lose a little of the benefits of react-redux, which has slightly superior equality checking

react-redux has _zero_ equality checking! That's up to `shouldComponentUpdate`. EP `useStoreState` is equivalent to using `PureComponent` for your class. However if you 'create an object' in `mapStateToProps`, that also will _break_ PureComponent.

Adding a `computed` value seems _equivalent_ to writing mapStateToProps. It's slightly more verbose _because_ it provides equality-checking, which mapStateToProps does not.

**Comment by allpro** [comment] 2019-07-25 15:43
> However, one small advantage with my useEasyActions is the ability to pass paths...

That doesn't seem any easier, shorter or clearer. Just do this...

````javascript
const { attachPaymentMethod } = useStoreActions(x=> x.path.to.model);
const { submit  } = useStoreActions(x=> x.another.model);
````

**Comment by joelmoss** [comment] 2019-07-25 15:46
> That doesn't seem any easier, shorter or clearer

Yeah, we're nitpicking now 😏

User preference really, but I admit, my `useEasyActions` is not as useful as I first thought.

**Comment by joelmoss** [comment] 2019-07-25 15:47
> react-redux has zero equality checking

Maybe I'm misunderstanding then, but the React redux [docs](https://react-redux.js.org/using-react-redux/connect-mapstate#return-values-determine-if-your-component-re-renders) say otherwise.

> By default, React Redux decides whether the contents of the object returned from mapStateToProps are different using === comparison (a "shallow equality" check) on each fields of the returned object...

**Comment by allpro** [comment] 2019-07-25 15:52
> Yeah, we're nitpicking now

I wasn't criticizing. Just noting that existing syntax provides _similar_ brevity and clarity if you use destructing.

**Comment by joelmoss** [comment] 2019-07-25 15:52
> I wasn't criticizing. Just noting that existing syntax provides similar brevity and clarity if you use destructing.

I know bud, I was blaming more myself for nitpicking really 😏

**Comment by allpro** [comment] 2019-07-25 16:03
> By default, React Redux decides whether the contents of the object returned from mapStateToProps are different using === comparison

**I stand corrected.** I really meant it doesn't test _state value_ equality; only the _output_ of mapStateToProps is checked. If you _combine_ values into a new object inside mapStateToProps, as in your useStoreState example, the equality test will fail. So they are equivalent in this regard.

**Comment by joelmoss** [comment] 2019-07-25 16:09
So just to clarify; the following are NOT identical in terms of the equality check performed?

```javascript
// state object
{ foo: 'foo', bar: 'bar', baz: 'baz' }

// This would cause a re-render EVERY time any state is changed, including `baz`.
useStoreState(state => ({ foo: state.foo, bar: state.bar })

// This would cause a re-render ONLY when `foo` or `bar` is changed.
const mapStateToProps = state => ({ foo: state.foo, bar: state.bar })
```

**Comment by allpro** [comment] 2019-07-25 16:39
You are correct. It's shallow equal vs ===. So what you are really asking for is the equivalent of returning a props-like object, that is tested using shallow-equal.

This would probably be easiest as a _separate method_ like `useStoreProps`, which would apply shallow-equal instead of pure equality. This wouldn't interfere with the current 'pure' hook.

**Comment by joelmoss** [comment] 2019-07-25 16:47
That is one way, but I think that being able to pass a custom equality function to `useStoreState` is far more flexible...

```javascript
const equalityFunction = (newState, oldState) => {
  // Some equality check here to compare newState to oldState.
  // For example, we could use lodash's `isEqual`...
  return _.isEqual(newState, oldState)
}

useStoreState(state => ({ foo: state.foo, bar: state.bar }, equalityFunction)
```

If the equality function is not given, it uses the current strict equality check - maintaining the current functionility.

This obviously allows the user to perform any kind of comparison that they want without dictating too much.

**Comment by ctrlplusb** [comment] 2019-07-25 22:32
Nice convo! 😃

Yeah, I definitely see the merits of the equality function. Likely to add this @joelmoss  👍

**Comment by allpro** [comment] 2019-07-27 15:26
````javascript
useStoreState(state => ({ foo: state.foo, baz: !state.bar }), equalityFunction);
````

**If you add the ability to pass an equality function like this, it would be nice to _also_ accept an options-hash.** I think most uses of this (possibly 99.99%!) would be shallow-equal. Rather than require a separate utility import for this basic need, an 'equality type' could be accepted, _something like:_

````javascript
useStoreState(state => ({ foo: state.foo, baz: !state.bar }), { shallowEqual: true });
````

A shallow-equal method is just a couple lines of code so would not bloat the library.

Shallow-equal is the _standard comparison_ offered by React (props/state) and React-Redux (mapStateToProps), so this would replicate that. Anything more complex can be handled by a _custom_ equalityFunction.

**Comment by tamagokun** [comment] 2019-09-24 12:37
wanted to call out that react-redux uses this method for its `useSelector` hook, and it's great. 
https://react-redux.js.org/next/api/hooks#useselector

```js
// potential future code :)
import { shallowEqual, useStoreState } from 'easy-peasy';

const data = useStoreState(mapState, shallowEqual);
```

It would be great if easy-peasy did this as well, or provide context so we can create our own hooks. Right now i'm using both easy-peasy and react-redux in a project so I can utilize this hook, but having the two providers and two contexts (StoreProvider and Provider) felt a little yucky.

**Comment by joelmoss** [comment] 2019-11-10 22:50
Just created a [PR](https://github.com/ctrlplusb/easy-peasy/pull/354) to add support for this. Feedback very welcome

**Comment by ctrlplusb** [comment] 2020-01-17 10:39
Closing this in favour of the open PR, which I plan to merge soon.

**Closed by ctrlplusb** 2020-01-17 10:39 UTC
Labels: docs, feature-request, question
