### ISSUE TITLE
Computed properties execute without being accessed

### ISSUE THREAD

**Issue by mkuklis** [ctrlplusb/easy-peasy#580] opened 2020-10-21 14:49 UTC
Hi @ctrlplusb, apologies for reporting this again but I'm still seeing some issues with computed properties executing by default in `v4.0.1`. I spent a bit of time and I was able to track it down. It basically happens when you have more than one model with action on one model and computed prop on another. When the action is executed and changes model's local state the computed prop on another model also executes. Here is a simple test to illustrate this:

````js
test('computed properties should not execute when not accessed', () => {
  let computedCount = 0;

  const store = createStore({
    user: {
      firstName: 'Mary',
      lastName: 'Poppins',
      fullName: computed(
        [(state) => state.firstName, (state) => state.lastName],
        (firstName, lastName) => {
          computedCount += 1;
          return `${firstName} ${lastName}`;
        },
      ),
      setFirstName: action((state, payload) => {
        state.firstName = payload;
      }),
    },
    group: {
      data: {},
      change: action((state) => {
        state.data.somedata = 1;
      }),
    }
  });

  store.getActions().group.change();

  // assert which currently fails
  expect(computedCount).toBe(0);
});
````

I noticed that when I turn this line off:

https://github.com/ctrlplusb/easy-peasy/blob/71ad696f3780a1d67cc8c865e56db3d661d0cb9d/src/extract-data-from-model.js#L172

I see a correct behavior but of course my understanding of the code is pretty limited.

**Comment by mkuklis** [comment] 2020-10-21 15:15
Perhaps the issue here is related to action reducers not executing in the right scope?

**Comment by ctrlplusb** [comment] 2020-10-22 12:13
Hi @mkuklis 👋

Thanks for raising this issue. It's an important regression to consider, especially for those making use of expensive computed properties.

I had a dive into the why and how and basically it's due to a downstream change in behaviour within the Immer package. There are some important changes being made to optimize Immer which unfortunately will have an impact on libraries that are utilizing Immer in more exotic manners.

I bashed my head with some crazy ideas, but each attempt brought along with some very unwanted side effects. In the end the best solution I could come up with is to not expose computed properties to actions.

```javascript
const model = {
  todos: [],
  todoCount: computed(state => state.todos.length),
  addTodo: action((state, payload) => { 
    // This would no longer work. Accessing computed properties would return
    // an `undefined` value
    //          👇
    if (state.todoCount < MAX_TODO_COUNT) {
      state.todos.push(payload);
    }
  }),
}
```

Setting this restriction would allow me to continue the performance guarantees you are expecting (i.e. computed properties are only computed when being consumed).

It's a breaking change, however, I personally feel like it isn't a major one. I feel like having the performance guarantees are worth it.

I'd appreciate your thoughts, or that of others...

**Comment by mkuklis** [comment] 2020-10-22 14:21
@ctrlplusb thank you so much for your time on this and to even consider fixing it. I do think this should be addressed because otherwise people can run into some very surprising scenarios. As you also mentioned performance is another thing to consider.

I like what you are proposing here. The downside is that it is a breaking change but it's nice to see there is a workaround with `thunks`.

I reviewed our source code (around 30 models) and I haven't seen a single case where computed prop is used inside the action. I did find one case where computed prop was used inside another computed prop (probably not a right thing to do anyway).

Thank you again @ctrlplusb for all your work on this.

**Comment by ctrlplusb** [comment] 2020-10-22 14:42
Thanks for the feedback @mkuklis - very helpful to hear your own real world experience.

> I reviewed our source code (around 30 models) and I haven't seen a single case where computed prop is used inside the action. I did find one case where computed prop was used inside another computed prop (probably not a right thing to do anyway).

This should be ok still 🙏

**Comment by ctrlplusb** [comment] 2020-10-27 20:17
Will be in next release. 👍

**Closed by ctrlplusb** 2020-10-27 20:17 UTC
Labels: breaking-change, bug, feedback-wanted
