### ISSUE TITLE
Access state directly in thunk action

### ISSUE THREAD

**Issue by lyyourc** [ctrlplusb/easy-peasy#109] opened 2019-02-28 06:17 UTC
Provide a easy way to access state:

```ts
const todoModal = {
  skip: 0,
  limit: 10,
  list: [],

  // Before:
  fetchTodos: thunk(async (actions, { skip }, helpers) => {
     // access state via helpers 👎
    const { limit } = helpers.getState().todos
    await todoServices.fetchTodos({ limit, skip })
  }),

  // After:
  // access state directly 👍
  fetchTodos: thunk(async (state, actions, { skip }, helpers) => {
    const { limit } = state
    await todoServices.fetchTodos({ limit, skip })
  }),
}

```

**Comment by ctrlplusb** [comment] 2019-02-28 07:57
Duplicate of #101

**Closed by ctrlplusb** 2019-02-28 07:57 UTC
