### ISSUE TITLE
Can't map useStoreState when redirected to other component after login.

### ISSUE THREAD

**Issue by csulit** [ctrlplusb/easy-peasy#475] opened 2020-04-16 11:51 UTC
Unhandled Rejection (Error): An error occurred trying to map state in a useStoreState hook: Cannot read property 'sites' of undefined

but after I reload the page it fetches data w/o error.

**Comment by ctrlplusb** [comment] 2020-04-16 13:18
Hey @csulit 👋

Sorry to hear you are experiencing some issues.

In order for me to be able to assist debug this for you would you mind creating a minimal reproduction within CodeSandbox?

✌️

**Comment by cstrnt** [comment] 2020-07-02 09:08
Having the same issue here. The problem looks like this
```
  const { getBoardData, setBoardId } = useStoreActions((actions) => actions.board);
  useEffect(() => {
    if (router.query.boardId) {
      setBoardId(router.query.boardId as string);
      getBoardData()
        .then(() => setLoading(false))
        .catch(() => {
          router.replace(`/login`);
        });
    }
  }, [router.query.boardId]);
```

**Comment by ctrlplusb** [comment] 2022-09-16 06:14
Closing as there has been no further activity on this for 2 years. 😅

**Closed by ctrlplusb** 2022-09-16 06:14 UTC
