### ISSUE TITLE
Type Error: 'actions' Object is of type 'unkown'

### ISSUE THREAD

**Issue by ramandhingra** [ctrlplusb/easy-peasy#348] opened 2019-11-06 13:10 UTC
I encounter this error in the following code

`
const unsetUserFromStore = useStoreActions(
   actions => actions.userModel.logout
  )
`

The following code works OK because I  assigned a type 'any' to 'actions'
`
const unsetUserFromStore = useStoreActions(
   (actions: any) => actions.userModel.logout
  )
`

But I want to avoid using 'any' TypeScript type. What exactly should be the 'actions' type?

Thanks

**Comment by ctrlplusb** [comment] 2019-11-06 13:54
Have you followed the TypeScript tutorial? Specifically;

https://easy-peasy.now.sh/docs/typescript-tutorial/typed-hooks.html

**Comment by ramandhingra** [comment] 2019-11-06 14:22
Yes I did. I am using typed-hooks.

**Comment by ctrlplusb** [comment] 2019-11-06 17:09
Could you create a minimal example in codesandbox for me please?

**Comment by ramandhingra** [comment] 2019-11-08 02:12
I will do it in another few days. Thank you.

**Comment by mesvil7** [comment] 2019-11-20 14:12
You can export de action model in you store file


**store-file**
```
import { createStore, createTypedHooks, Actions, State } from 'easy-peasy'

interface StoreModel {
  user: UserModel
}

export type IStateModel = State<StoreModel>
export type IActionModel = Actions<StoreModel>
```

**component**
```
import { useStoreActions, IActionModel } from 'store'

const unsetUserFromStore = useStoreActions(
    (actions: IActionModel): any => actions.user.logout
  )
```

**Comment by ctrlplusb** [comment] 2020-01-17 10:40
Closing due to lack of reproduction.

**Closed by ctrlplusb** 2020-01-17 10:40 UTC
Labels: need-more-info
