### ISSUE TITLE
 Cannot set property 'isManual' of undefined

### ISSUE THREAD

**Issue by kratam** [ctrlplusb/easy-peasy#394] opened 2020-01-07 10:23 UTC
I'm having a weird issue. My app works fine when I run it in Chrome "normally", but if I activate the device toolbar (cmd+shift+m in osx) to check the page in an emulated mobile device, I get this error whenever an action is called:

```
Uncaught TypeError: Cannot set property 'isManual' of undefined
    at Immer.createDraft (modules.js?hash=b35eebe1479184da68c648f9d03598b8cafe9c20:10107)
    at simpleProduce (modules.js?hash=b35eebe1479184da68c648f9d03598b8cafe9c20:8162)
    at runActionReducerAtPath (modules.js?hash=b35eebe1479184da68c648f9d03598b8cafe9c20:8179)
    at reducerForActions (modules.js?hash=b35eebe1479184da68c648f9d03598b8cafe9c20:8189)
    at rootReducer (modules.js?hash=b35eebe1479184da68c648f9d03598b8cafe9c20:8208)
    at p (<anonymous>:1:36402)
    at v (<anonymous>:1:36684)
    at <anonymous>:1:40069
    at Object.dispatch (modules.js?hash=b35eebe1479184da68c648f9d03598b8cafe9c20:10642)
    at e (<anonymous>:1:40553)
```

I'm totally clueless.

**Comment by ctrlplusb** [comment] 2020-01-08 14:20
Hi @kratam 

I'd be happy to help if you could provide me with a minimal reproduction via [codesandbox.io](https://codesandbox.io/s/wizardly-jepsen-yv76p30w8v).

👍

**Comment by ctrlplusb** [comment] 2020-03-31 13:03
Closing this due to lack of reproduction.

**Closed by ctrlplusb** 2020-03-31 13:03 UTC
Labels: need-more-info
