### ISSUE TITLE
Have the ability to destruct `useState`

### ISSUE THREAD

**Issue by hutber** [ctrlplusb/easy-peasy#162] opened 2019-04-30 17:15 UTC
Current implimentation:

```
state = {
    form: true,
    balls: false
}
  const stockListStore = useStore(state => state.form);
  const balls = useStore(state => state.balls);
```

**Comment by ctrlplusb** [comment] 2019-04-30 21:14
Is this a duplicate of #163? Closing.

**Closed by ctrlplusb** 2019-04-30 21:14 UTC

**Comment by hutber** [comment] 2019-04-30 22:39
Odd indeed, I edited this ticket. But it created a new one instead. Thanks for closing and answering.
