### ISSUE TITLE
Computed properties execute even if they are not currently being accessed.

### ISSUE THREAD

**Issue by mkuklis** [ctrlplusb/easy-peasy#462] opened 2020-03-27 18:32 UTC
Hi @ctrlplusb,

We ran into an issue with computed properties. It seems like computed properties which are currently not being accessed also execute which cause all sorts of weird problems.

Here is a simple example:

````js

const userModel = {
  data: {},
  withBlocked: computed(
    [state => state.data],
    user => {
      // computed body
    },
  ),
  withFriends: computed(
    [state => state.data],
    user => {
      // computed body
    },
  ),
  authorize: action((state, payload) => {
    state.data = payload;
  }),
  unauthorize: action(state => (state.data = {})),
};
````

now somewhere else when we execute:

````js
const actions = store.getActions();
actions.user.unauthorize();
````

both `withBlocked` and `withFriends` will be fired even though they are not used anywhere.

This maybe related to https://github.com/ctrlplusb/easy-peasy/issues/446

I started to look at the source code and I think the issue could be related to: https://github.com/ctrlplusb/easy-peasy/blob/master/src/create-reducer.js#L48

Although this probably requires a bigger refactor in order to track which computed props are currently utilized.

**Comment by ctrlplusb** [comment] 2020-03-27 22:19
Hi @mkuklis

I have already tracked this down. ☺️

A fix is in the works. It has to do with the way immer is working. I will be pushing a patch onto the 3.4.0 alpha branch soonish and will ping you to ask you to test it. 👍

**Comment by ctrlplusb** [comment] 2020-03-27 23:51
Hey @mkuklis 

I have updated https://github.com/ctrlplusb/easy-peasy/pull/459

The alpha now includes the patched `immer`. You should no longer be experiencing unexpected executions of your computed properties. Please can you try the alpha and report back.

**Comment by mkuklis** [comment] 2020-03-28 19:36
Wow thank you for such a quick turnaround with this @ctrlplusb! 

I just tried the alpha version `easy-peasy@3.4.0-alpha.5` with immer `v6.0.2` but I now see different errors:

```js
Uncaught Error: [Immer] Immer drafts cannot have computed properties
    at die (immer.cjs.development.js:76)
    at immer.cjs.development.js:207
    at immer.cjs.development.js:129
    at Array.forEach (<anonymous>)
    at each (immer.cjs.development.js:128)
    at shallowCopy (immer.cjs.development.js:198)
    at prepareCopy (immer.cjs.development.js:633)
    at Object.set (immer.cjs.development.js:531)
    at userModel.js:42
    at easy-peasy.cjs.js:344
````

The userModel.js in this case is just a simple action with:

```js
  unauthorize: action(state => {
    state.data = {};
  }),
````

Perhaps I'm doing something wrong here although this worked fine before.

**Comment by ctrlplusb** [comment] 2020-03-29 14:20
Hey @mkuklis

It looks like the patch on `immer` didn't run as expected.

Can you please try remove your node_modules and do a fresh install?

**Comment by velsa** [comment] 2020-03-30 12:56
Trying `easy-peasy@3.4.0-alpha.5` as well, since I have a similar issue with computed being fired every time the action is called. 

I get the following:

```
TypeScript error in ...
This expression is not callable.
Type 'Computed<IAlertsModel, (filter: { ... }, isResolved: boolean) => 
IAlert[], IRootStoreModel>' has no call signatures.  TS2349
```

Basically, all computed functions in my models have this error.

If I manually add `"immer": "^6.0.2",` to `package.json` – nothing changes.
And of course, as per your advice, I have removed `node_modules/` and did a fresh install every time I changed `package.json`

Version 3.3.0 works with no issues.

**Comment by ctrlplusb** [comment] 2020-03-30 12:59
Thanks for the feedback both. I am investigating. 👍

**Comment by mkuklis** [comment] 2020-03-30 17:37
@ctrlplusb just some feedback for you :)

It looks like the `npm run postinstall` is not executing correctly because the `patches` folder is missing.
Also it looks like something didn't go right in this file (maybe it's related):

https://github.com/ctrlplusb/easy-peasy/blob/v3.4.0/patches/immer%2B6.0.2.patch

**Comment by mkuklis** [comment] 2020-03-30 18:19
A bit more feedback for you.

I created the `patches` folder by hand under `easy-peasy` and copied the patch:

https://github.com/ctrlplusb/easy-peasy/blob/v3.4.0/patches/immer%2B6.0.2.patch

after than when I ran `npm run postinstall`

I would get this error:

`Patch file found for package immer which is not present at node_modules/immer`

this is because the `patch-package` is looking for immer under `easy-peasy/node_modules/immer` but immer actually sits under my app's `node_modules`. I copied it under `easy-peasy/node_modules` then run:

`npm run postinstall`

and finally got:

````
Applying patches...
immer@6.0.2 ✔
````

after that I copied it back under my app's node_modules and everything now works as expected. The computed props don't execute anymore!

**Comment by ctrlplusb** [comment] 2020-03-31 01:06
Awesome feedback @mkuklis!

Great to hear that fundamentally the patch works. I am working on a script to ensure the patch is installed as expected. I've already published a new version that includes the patch files. Doh. ☺️

Will feedback here when it's ready for another round of testing.

**Comment by ctrlplusb** [comment] 2020-03-31 12:02
@mkuklis 

I have just published `easy-peasy@3.4.0-alpha.9`.

I would appreciate it if you could try remove your node_modules and then do a fresh install with this version. The patch should be applied correctly. 🤞

**Comment by ctrlplusb** [comment] 2020-03-31 12:11
@velsa - it looks like you are actually reporting an issue with the TypeScript definitions.

I'll try recreate your issue on the 3.4.0 branch. 👍

**Comment by mkuklis** [comment] 2020-03-31 15:44
@ctrlplusb thank you. Everything works as expected now in `easy-peasy@3.4.0-alpha.9`. Nice job!

**Comment by ctrlplusb** [comment] 2020-04-01 11:53
@velsa - apologies, that was a regression in the TypeScript definitions. I have patched them and added a test case for your use case. All appears to be working as expected again. Please try it out and let me know. 👍

**Closed** 2020-04-13 16:20 UTC
Labels: improvement
