### ISSUE TITLE
Incorrect typescript type when using a function to generate Models with generic types

### ISSUE THREAD

**Issue by williammetcalf** [ctrlplusb/easy-peasy#300] opened 2019-08-20 18:39 UTC
(duplicate of https://github.com/ctrlplusb/easy-peasy/issues/189, but it seems to have broken again)

I am trying to make a model factory function to generate simple models with just a value and a setter action, where the value is of a generic type. When doing this the action's state isn't correctly typed.

example: 
```tsx
import { Action, action } from "easy-peasy";

interface SimpleModel<T> {
  value: T;
  set: Action<SimpleModel<T>, T>;
}

function makeSimpleModel<T>(initialValue: T): SimpleModel<T> {
  return {
    value: initialValue,
    set: action((state, payload) => {
      state.value = payload;
    })
  };
}

```

...and heres a quick code sandbox https://codesandbox.io/s/sparkling-cookies-4tx0m (doesn't do anything functional, just to demonstrate the red squiggly)

This generates a compiler error:
```
Property 'value' does not exist on type '_Merge<StateMapper<_Pick<_Pick<ListModel<T>, ({ 1: never; 0: "value"; }[Extends<T, ActionTypes>] & "value") | ({ 1: never; 0: "value"; }[Extends<T, ActionTypes>] & "set") | ({ 1: never; 0: "value"; }[Extends<...>] & "add") | ({ ...; }[Extends<...>] & "remove")>, (Exclude<...> & ... 1 more ... & "value") | ... 14 mor...'.ts(2339)
```

easy-peasy version: 3.0.2 (most recent)
typescript version: 3.5.3 (most recent)

**Comment by ctrlplusb** [comment] 2019-08-20 19:27
Hmmm on train but can you change the generic to "T extends object"

**Comment by williammetcalf** [comment] 2019-08-20 19:36
> Hmmm on train but can you change the generic to "T extends object"

This doesn't change anything, still getting the same compile error

**Comment by pirix-gh** [comment] 2019-09-10 21:41
@ctrlplusb, is this related to what we'd discussed?

**Comment by ctrlplusb** [comment] 2019-09-11 15:21
@pirix-gh it is indeed. I haven't had time to apply the alternative strategy you proposed. 😃

**Comment by ctrlplusb** [comment] 2019-10-01 20:51
@williammetcalf this is a difficult case as the issue is that `T` could be an `Action` or any other type that our statemapper tries to strip out of your model definition when resolving the type for the state argument.

A workaround is to introduce a simple "tuple" type wrapper for `T`. This basically forces Typescript to know that the value will never be one of the types it wants to filter, as it is boxed in a valid state type.

For example...

```typescript
type Value<T> = [T];

interface SimpleModel<T> {
  thevalue: Value<T>;
  theset: Action<SimpleModel<T>, T>;
}

const makeSimpleModel = <T>(initialValue: T): SimpleModel<T> => {
  return {
    thevalue: [initialValue],
    theset: action((state, payload) => {
      state.thevalue = [payload];
    }),
  };
};
```

**Closed** 2020-04-13 16:24 UTC
Labels: bug, typescript

**Comment by liamdefty** [comment] 2021-11-16 12:38
Just commenting that I was still running into this issue. I followed the workaround advised by @ctrlplusb but wondered if there has been any progress

Also for anyone else running into this issue, so we don't have to unbox the tuple every time we needed it, I also added it as a computed value which has worked nice for my needs but would be interested if anyone sees any negatives to this

```ts
import { Thunk, Action, action, thunk, Computed, computed } from 'easy-peasy';
import { getErrorCode, ErrorCode } from '@data-access-client';

// @see https://github.com/ctrlplusb/easy-peasy/issues/300
type Value<T> = [T];

class FetchModel<T> {
  isBusy = false

  error: ErrorCode

  data?: Value<T>

  value: Computed<FetchModel<T>, T | undefined> = computed(state => state.data?.[0])

  execute: Thunk<FetchModel<T>, T> = thunk(
    async (actions, payload, helpers) => {
      actions.start()
      try {
        const data = await helpers.injections.fetcher(payload);
        actions.finish({ data })
        return data;
      } catch (error) {
        actions.finish({ error: getErrorCode(error) });
        helpers.fail(error);
        throw error;
      }
    }
  );

  start: Action<FetchModel<T>> = action((state) => {
    state.isBusy = true;
    state.error = undefined;
  });

  finish: Action<FetchModel<T>, { data?: Value<T> , error?: ErrorCode }> = action(
    (state, { data, error }) => {
      state.isBusy = false;
      state.error = error;
      state.data = data;
    }
  )
}

export default FetchModel;
```
